<?xml version="1.0" encoding="utf-8"?><Database Name="ICSDB" Class="DBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\ICSDB.mdf;Integrated Security=True" SettingsObjectName="ElectronicICS.My.MySettings" SettingsPropertyName="ICSDBConnectionString" Provider="System.Data.SqlClient" />
</Database>